# Generated by Django 6.0.4 on 2026-04-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='description',
        ),
    ]
