# Generated by Django 6.0.4 on 2026-04-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0002_remove_servicetype_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='company',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
