# Generated by Django 6.0.4 on 2026-04-29 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0004_branchservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_branches', to='service_management.servicetype'),
        ),
    ]
