# Generated by Django 4.0 on 2026-05-08 04:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0016_customervehicle_vehicle_type'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0004_schemetype'),
        ('service_management', '0006_branchvehicleprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVehicleTypePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_vehicle_prices', to='client_management.branch')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_prices', to='service_management.servicetype')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='master.vehicletype')),
            ],
            options={
                'unique_together': {('branch', 'service', 'vehicle_type')},
            },
        ),
    ]
