# Generated by Django 4.0 on 2026-05-08 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0007_servicevehicletypeprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevehicletypeprice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_prices', to='service_management.service'),
        ),
    ]
