# Generated by Django 4.0 on 2026-05-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0008_alter_servicevehicletypeprice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
    ]
