# Generated by Django 6.0.4 on 2026-05-12 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0016_customervehicle_vehicle_type'),
        ('master', '0004_schemetype'),
        ('service_management', '0009_remove_service_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicevehicletypeprice',
            unique_together={('branch', 'service', 'vehicle_model')},
        ),
        migrations.AddField(
            model_name='servicevehicletypeprice',
            name='vehicle_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='master.vehicletypemodel'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='servicevehicletypeprice',
            name='vehicle_type',
        ),
    ]
