# Generated by Django 4.0 on 2026-05-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_schemetype'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client_management', '0016_customervehicle_vehicle_type'),
        ('service_management', '0010_companyservice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicevehicletypeprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servicevehicletypeprice',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_type_prices', to='master.vehicletypemodel'),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user'),
        ),
        migrations.AlterUniqueTogether(
            name='servicevehicletypeprice',
            unique_together={('branch', 'service', 'vehicle_model')},
        ),
        migrations.RemoveField(
            model_name='servicevehicletypeprice',
            name='vehicle_type',
        ),
    ]
