# Generated by Django 4.0 on 2026-05-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0011_alter_servicevehicletypeprice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_branches', to='service_management.service'),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_service_entries', to='service_management.service'),
        ),
    ]
