# Generated by Django 4.0 on 2026-07-21 05:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0041_add_slug_branch_service_category'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service_management', '0012_change_service_fk_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='slug',
            field=models.SlugField(blank=True, help_text='Machine-readable key: washing | oil_change | tyre_change | wheel_alignment', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BranchServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_categories', to='client_management.branch')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_categories', to='service_management.servicetype')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'unique_together': {('branch', 'service_type')},
            },
        ),
    ]
