# Generated by Django 4.0 on 2026-09-16 05:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0053_customervehicle_emission_standard_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0033_alter_vehicletypemodel_unique_together_and_more'),
        ('service_management', '0014_seed_service_type_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmokeTestPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoke_test_prices', to='client_management.branch')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('emission_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoke_test_prices', to='master.emissionstandard')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoke_test_prices', to='master.vehicletypemodel')),
            ],
            options={
                'ordering': ['vehicle_model__name', 'emission_standard__name'],
                'unique_together': {('branch', 'vehicle_model', 'emission_standard')},
            },
        ),
    ]
