# Generated by Django 4.0 on 2026-09-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0055_quotationextra_quantity_quotationextra_remarks_and_more'),
        ('master', '0033_alter_vehicletypemodel_unique_together_and_more'),
        ('service_management', '0015_smoketestprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smoketestprice',
            options={'ordering': ['vehicle_model__name', 'emission_standard__name', 'fuel_type']},
        ),
        migrations.AlterUniqueTogether(
            name='smoketestprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='smoketestprice',
            name='fuel_type',
            field=models.CharField(choices=[('ALL', 'All Fuel Types'), ('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('LPG', 'LPG'), ('ELECTRIC', 'Electric')], default='ALL', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='smoketestprice',
            unique_together={('branch', 'vehicle_model', 'emission_standard', 'fuel_type')},
        ),
    ]
