# Generated by Django 4.0 on 2026-09-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0016_alter_smoketestprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sac_code',
            field=models.CharField(blank=True, help_text='Services Accounting Code (SAC)', max_length=50, null=True),
        ),
    ]
