# Generated by Django 4.0 on 2026-05-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='raw_password',
            field=models.CharField(blank=True, help_text='Stored plain text password', max_length=128, null=True),
        ),
    ]
