# Generated by Django 5.2.14 on 2026-07-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_app_open',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last app activity/open', null=True),
        ),
    ]
