# Generated by Django 4.0 on 2026-05-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_schemetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.CharField(blank=True, help_text='e.g. INR, AED', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(blank=True, help_text='e.g. ₹, AED', max_length=10, null=True),
        ),
    ]
