# Generated by Django 4.0 on 2026-06-12 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0028_stock_expense_head'),
        ('master', '0007_expense_expenseentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensehead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_management.client'),
        ),
    ]
