# Generated by Django 4.0 on 2026-07-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_seed_colors_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecompany',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, related_name='companies', to='master.VehicleType'),
        ),
    ]
