# Generated by Django 4.0 on 2026-07-02 10:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client_management', '0036_remove_customervehicle_company'),
        ('master', '0012_seed_vehicle_types_and_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrandModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
                ('vehicle_type_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_models', to='master.vehicletypemodel')),
            ],
            options={
                'ordering': ['vehicle_type_model__name', 'name'],
                'unique_together': {('vehicle_type_model', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='VehicleCompany',
        ),
    ]
