# Generated by Django 4.0 on 2026-07-21 05:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0041_add_slug_branch_service_category'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('finance_management', '0008_add_slug_branch_service_category'),
        ('master', '0016_expenseentry_paid_amount_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('brand', models.CharField(help_text='e.g. Castrol, Mobil 1, Shell', max_length=100)),
                ('name', models.CharField(help_text='Product name e.g. GTX, Edge, Helix', max_length=150)),
                ('grade', models.CharField(help_text='Viscosity grade e.g. 5W-30, 10W-40', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_products', to='client_management.client')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'ordering': ['brand', 'name'],
                'unique_together': {('company', 'brand', 'name', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='OilStockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(choices=[('in', 'Stock In (Purchase)'), ('out', 'Stock Out (Used in Service)')], max_length=5)),
                ('quantity_litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_transactions', to='client_management.branch')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('oil_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='master.oilproduct')),
                ('reference_invoice', models.ForeignKey(blank=True, help_text='Linked invoice for stock-out entries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_transactions', to='finance_management.invoice')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TyreBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('brand', models.CharField(help_text='e.g. MRF, Apollo, Bridgestone, CEAT', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_brands', to='client_management.client')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'ordering': ['brand'],
                'unique_together': {('company', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='OilStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity_litres', models.DecimalField(decimal_places=2, default=0, help_text='Current stock in litres', max_digits=10)),
                ('low_stock_alert_litres', models.DecimalField(decimal_places=2, default=5, help_text='Alert when stock falls below this level', max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_stocks', to='client_management.branch')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('oil_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='master.oilproduct')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'unique_together': {('branch', 'oil_product')},
            },
        ),
    ]
