# Generated by Django 4.0 on 2026-07-21 10:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client_management', '0041_add_slug_branch_service_category'),
        ('master', '0017_add_slug_branch_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price_per_litre', models.DecimalField(decimal_places=2, help_text='Price charged per litre of this oil (e.g. 450.00)', max_digits=10)),
                ('recommended_qty_litres', models.DecimalField(blank=True, decimal_places=2, help_text='Recommended fill quantity for this vehicle (e.g. 4.0 for Sedan)', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_product_prices', to='client_management.client')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('oil_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='master.oilproduct')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
                ('vehicle_make', models.ForeignKey(blank=True, help_text='Leave blank to apply to all makes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_prices', to='master.vehiclemake')),
                ('vehicle_type', models.ForeignKey(blank=True, help_text='Leave blank to apply to all vehicle types', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_prices', to='master.vehicletype')),
            ],
            options={
                'ordering': ['oil_product__brand', 'oil_product__name'],
            },
        ),
    ]
