# Generated by Django 4.0 on 2026-07-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0041_add_slug_branch_service_category'),
        ('master', '0018_add_oil_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilproduct',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Leave blank for Superadmin global master', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oil_products', to='client_management.client'),
        ),
    ]
