# Generated by Django 4.0 on 2026-07-21 10:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0019_make_oil_product_company_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oilproduct',
            options={'ordering': ['oil_brand__name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='oilproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='price_per_litre',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price charged per litre of this oil (e.g. 450.00)', max_digits=10),
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='recommended_qty_litres',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recommended fill quantity for this vehicle (e.g. 4.0 for Sedan)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='vehicle_make',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all makes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_products', to='master.vehiclemake'),
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all vehicle types', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_products', to='master.vehicletype'),
        ),
        migrations.AlterField(
            model_name='oilproduct',
            name='brand',
            field=models.CharField(blank=True, help_text='Legacy string brand fallback', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oilproduct',
            name='grade',
            field=models.CharField(blank=True, help_text='Legacy string grade fallback', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oilproduct',
            name='name',
            field=models.CharField(blank=True, help_text='Product name e.g. GTX, Edge, Helix', max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='OilGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OilBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='oil_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='master.oilbrand'),
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='oil_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='master.oilgrade'),
        ),
    ]
