# Generated by Django 4.0 on 2026-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_add_oil_brand_grade_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilproduct',
            name='oil_run_km',
            field=models.PositiveIntegerField(default=5000, help_text='Number of KM this oil lasts for (e.g. 5000)'),
        ),
    ]
