# Generated by Django 4.0 on 2026-07-25 05:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0041_add_slug_branch_service_category'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0021_oilproduct_oil_run_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilFilterBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, help_text='Leave blank for global master', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oil_filter_brands', to='client_management.client')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OilFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Filter part number / model name e.g. OF-101', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price charged for this filter', max_digits=10)),
                ('running_km', models.PositiveIntegerField(default=5000, help_text='Recommended running KM for this oil filter e.g. 5000')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, help_text='Leave blank for global master', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oil_filters', to='client_management.client')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('oil_filter_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='master.oilfilterbrand')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'ordering': ['oil_filter_brand__name', 'name'],
            },
        ),
    ]
