# Generated by Django 4.0 on 2026-07-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_oilfilterbrand_oilfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilproduct',
            name='for_diesel',
            field=models.BooleanField(default=True, help_text='Suitable for Diesel vehicles'),
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='for_petrol',
            field=models.BooleanField(default=True, help_text='Suitable for Petrol vehicles'),
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='oil_run_days',
            field=models.PositiveIntegerField(default=180, help_text='Number of days duration this oil lasts for (e.g. 30, 90, 180 days)'),
        ),
    ]
