# Generated by Django 4.0 on 2026-07-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0042_stock_quantity'),
        ('master', '0026_create_tyre_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilfilter',
            name='stock_qty',
            field=models.IntegerField(default=0, help_text='Current stock quantity in units'),
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='category',
            field=models.CharField(choices=[('Engine Oil', 'Engine Oil'), ('Brake Fluid', 'Brake Fluid'), ('Power Steering Oil', 'Power Steering Oil'), ('Transmission Fluid', 'Transmission Fluid'), ('Differential Oil', 'Differential Oil'), ('Coolant', 'Coolant'), ('Gear Oil', 'Gear Oil'), ('Transfer Case Fluid', 'Transfer Case Fluid')], default='Engine Oil', help_text='Category of oil / fluid', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='client_management.branch'),
        ),
    ]
