# Generated by Django 5.2.14 on 2026-08-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0028_purchaseinvoice_stockgroup_and_more'),
    ]

    operations = [
    ]

