# Generated by Django 4.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0050_stock_brand'),
        ('master', '0031_supplier_type_credit_limit_no_of_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='client_management.client'),
        ),
    ]
