# Generated by Django 4.0 on 2026-08-20 01:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client_management', '0051_branch_enabled_vehicle_segments_and_more'),
        ('master', '0032_alter_vehicletypemodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicletypemodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vehicletypemodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_segments', to='client_management.client'),
        ),
        migrations.AddField(
            model_name='vehicletypemodel',
            name='disabled_companies',
            field=models.ManyToManyField(blank=True, related_name='disabled_global_vehicle_segments', to='client_management.Client'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicletypemodel',
            unique_together={('company', 'vehicle_type', 'name')},
        ),
        migrations.CreateModel(
            name='EmissionStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='e.g. BS-3, BS-4, BS-6, EV', max_length=100)),
                ('fuel_type', models.CharField(choices=[('ALL', 'All Fuel Types'), ('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('LPG', 'LPG'), ('ELECTRIC', 'Electric')], default='ALL', max_length=20)),
                ('validity_months', models.PositiveIntegerField(default=12, help_text='Smoke test validity in months (e.g. 6 or 12)')),
                ('reminder_1_days', models.PositiveIntegerField(default=15, help_text='1st reminder sent X days before expiry')),
                ('reminder_2_days', models.PositiveIntegerField(default=3, help_text='2nd reminder sent X days before expiry')),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'ordering': ['validity_months', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vehicletypemodel',
            name='emission_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_segments', to='master.emissionstandard'),
        ),
    ]
