# Generated by Django 4.2.30 on 2026-10-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0034_insurancecompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.CharField(blank=True, help_text='Flag emoji e.g. 🇮🇳, 🇸🇦', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='locale_tag',
            field=models.CharField(blank=True, help_text='BCP 47 locale tag e.g. en_IN, ar_SA', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='phone_dial_code',
            field=models.CharField(blank=True, help_text='Dial code e.g. +91, +966, +971', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='phone_iso_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 code e.g. IN, SA, AE', max_length=5, null=True),
        ),
    ]
