# Generated by Django 4.0 on 2026-05-14 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0018_branch_invoice_prefix'),
        ('finance_management', '0002_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='client_management.scheme'),
        ),
    ]
