# Generated by Django 4.0 on 2026-07-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0004_invoiceitem_add_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('digital_payments', 'Digital payments'), ('cheque', 'Cheque'), ('online', 'Online')], max_length=20),
        ),
    ]
