# Generated by Django 4.0 on 2026-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0005_alter_receipt_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('digital_payments', 'Digital payments')], max_length=20),
        ),
    ]
