# Generated by Django 4.0 on 2026-07-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0006_alter_receipt_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('cashinvoice', 'Cash Invoice'), ('creditinvoice', 'Credit Invoice')], default='cashinvoice', max_length=20),
        ),
    ]
