# Generated by Django 4.0 on 2026-07-21 05:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('finance_management', '0007_invoice_invoice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceServiceDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('service_category', models.CharField(choices=[('washing', 'Washing'), ('oil_change', 'Oil Change'), ('tyre_change', 'Tyre Change'), ('wheel_alignment', 'Wheel Alignment')], max_length=30)),
                ('oil_litres_used', models.DecimalField(blank=True, decimal_places=2, help_text='Litres of oil used in this service', max_digits=6, null=True)),
                ('oil_filter_changed', models.BooleanField(default=False)),
                ('odometer_at_service', models.PositiveIntegerField(blank=True, help_text='Vehicle km at time of service', null=True)),
                ('next_oil_change_km', models.PositiveIntegerField(blank=True, help_text='Recommended next oil change odometer reading', null=True)),
                ('next_oil_change_date', models.DateField(blank=True, help_text='Recommended next oil change date (optional)', null=True)),
                ('tyre_size', models.CharField(blank=True, help_text='e.g. 195/65 R15', max_length=50)),
                ('tyres_changed_count', models.PositiveSmallIntegerField(default=0, help_text='Number of tyres replaced (0-4)')),
                ('next_tyre_change_km', models.PositiveIntegerField(blank=True, help_text='Recommended next tyre change odometer reading', null=True)),
                ('next_tyre_change_date', models.DateField(blank=True, help_text='Recommended next tyre change date', null=True)),
                ('alignment_done', models.BooleanField(default=False)),
                ('balancing_done', models.BooleanField(default=False)),
                ('alignment_notes', models.TextField(blank=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('invoice_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_detail', to='finance_management.invoiceitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
