# Generated by Django 4.0 on 2026-07-21 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_add_slug_branch_service_category'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('finance_management', '0008_add_slug_branch_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservicedetail',
            name='oil_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', to='master.oilproduct'),
        ),
        migrations.AddField(
            model_name='invoiceservicedetail',
            name='tyre_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', to='master.tyrebrand'),
        ),
        migrations.AddField(
            model_name='invoiceservicedetail',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user'),
        ),
    ]
