# Generated by Django 4.0 on 2026-07-25 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_oilfilterbrand_oilfilter'),
        ('finance_management', '0009_add_slug_branch_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservicedetail',
            name='oil_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', to='master.oilfilter'),
        ),
        migrations.AddField(
            model_name='invoiceservicedetail',
            name='oil_filter_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price charged for oil filter', max_digits=10, null=True),
        ),
    ]
