# Generated by Django 4.0 on 2026-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0010_invoiceservicedetail_oil_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservicedetail',
            name='next_smoke_test_date',
            field=models.DateField(blank=True, help_text='Calculated next smoke test renewal date', null=True),
        ),
        migrations.AddField(
            model_name='invoiceservicedetail',
            name='smoke_test_period_months',
            field=models.PositiveIntegerField(blank=True, help_text='Renewal period in months (6 or 12)', null=True),
        ),
        migrations.AlterField(
            model_name='invoiceservicedetail',
            name='service_category',
            field=models.CharField(choices=[('washing', 'Washing'), ('oil_change', 'Oil Change'), ('tyre_change', 'Tyre Change'), ('wheel_alignment', 'Wheel Alignment'), ('smoke_test', 'Smoke Test')], max_length=30),
        ),
    ]
