# Generated by Django 4.0 on 2026-08-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0051_branch_enabled_vehicle_segments_and_more'),
        ('finance_management', '0011_invoiceservicedetail_next_smoke_test_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_operational',
            field=models.BooleanField(default=False, help_text='True if stock item was consumed operationally (0 rate)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='net_taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.stock'),
        ),
        migrations.AddField(
            model_name='invoiceservicedetail',
            name='next_alignment_km',
            field=models.PositiveIntegerField(blank=True, help_text='Recommended next wheel alignment & balancing odometer reading', null=True),
        ),
        migrations.AddField(
            model_name='invoiceservicedetail',
            name='warranty_unit',
            field=models.CharField(blank=True, help_text="Warranty unit ('month' or 'year')", max_length=10),
        ),
        migrations.AddField(
            model_name='invoiceservicedetail',
            name='warranty_value',
            field=models.PositiveIntegerField(blank=True, help_text='Warranty duration value (e.g. 6)', null=True),
        ),
        migrations.AlterField(
            model_name='invoiceservicedetail',
            name='service_category',
            field=models.CharField(choices=[('washing', 'Washing'), ('oil_change', 'Oil Change'), ('tyre_change', 'Tyre Change'), ('wheel_alignment', 'Wheel Alignment'), ('smoke_test', 'Smoke Test'), ('car_detailing', 'Car Detailing')], max_length=30),
        ),
    ]
