# Generated by Django 4.0 on 2026-09-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0052_whatsapptemplate_wawy_template_name'),
        ('finance_management', '0012_invoice_remarks_invoiceitem_is_operational_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='assigned_staffs',
            field=models.ManyToManyField(blank=True, related_name='assigned_invoices', to='client_management.Staff'),
        ),
    ]
