# Generated by Django 4.0 on 2026-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0013_invoice_assigned_staffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='show_warranty_in_pdf',
            field=models.BooleanField(default=False, help_text='Include Warranty & Free Top-Up details in invoice PDF'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='show_warranty_in_pdf',
            field=models.BooleanField(default=False, help_text='Include Warranty & Free Top-Up details in invoice PDF'),
        ),
    ]
