# Generated by Django 4.0 on 2026-10-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0034_insurancecompany'),
        ('finance_management', '0016_alter_invoiceservicedetail_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservicedetail',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', to='master.insurancecompany'),
        ),
    ]
