# Generated by Django 4.0 on 2026-10-03 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0060_insurance_customer_fields'),
        ('finance_management', '0017_invoiceservicedetail_insurance_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.extra'),
        ),
    ]
