# Generated by Django 4.0 on 2026-10-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0018_invoiceitem_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
