# Generated by Django 6.0.4 on 2026-04-23 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0002_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.AddField(
            model_name='client',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.area'),
        ),
    ]
