# Generated by Django 6.0.4 on 2026-04-29 03:55

import client_management.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0003_remove_client_city_client_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo_bw',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos/bw/', validators=[client_management.models.validate_png, client_management.models.validate_image_dimensions]),
        ),
        migrations.AddField(
            model_name='client',
            name='logo_color',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos/color/', validators=[client_management.models.validate_png, client_management.models.validate_image_dimensions]),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('usage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('no_of_licenses', models.PositiveIntegerField(default=1)),
                ('whatsapp_integration', models.BooleanField(default=False)),
                ('bulk_sms', models.BooleanField(default=False)),
                ('email_integration', models.BooleanField(default=False)),
                ('bluetooth_printing', models.BooleanField(default=False)),
                ('tally_integration', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='client_management.client')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
