# Generated by Django 6.0.4 on 2026-04-24 12:07

import client_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0003_remove_client_city_client_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo_bw',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos/bw/', validators=[client_management.models.validate_png, client_management.models.validate_image_dimensions]),
        ),
        migrations.AddField(
            model_name='client',
            name='logo_color',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos/color/', validators=[client_management.models.validate_png, client_management.models.validate_image_dimensions]),
        ),
    ]
