# Generated by Django 6.0.4 on 2026-04-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0007_branchvehicleprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchVehiclePrice',
        ),
    ]
