# Generated by Django 4.0 on 2026-05-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0010_customer_customervehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customervehicle',
            old_name='vehicle_model',
            new_name='vehicle_type_model',
        ),
        migrations.RemoveField(
            model_name='customervehicle',
            name='vehicle_type',
        ),
    ]
