# Generated by Django 6.0.4 on 2026-05-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0013_client_business_name_client_licenses_count_and_more'),
        ('master', '0004_schemetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='scheme_types',
            field=models.ManyToManyField(blank=True, to='master.schemetype'),
        ),
    ]
