# Generated by Django 4.0 on 2026-05-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_schemetype'),
        ('client_management', '0014_branch_scheme_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='scheme_types',
            field=models.ManyToManyField(blank=True, to='master.SchemeType'),
        ),
        migrations.AlterField(
            model_name='client',
            name='scheme_types',
            field=models.ManyToManyField(blank=True, to='master.SchemeType'),
        ),
    ]
