# Generated by Django 6.0.4 on 2026-05-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0015_alter_branch_scheme_types_alter_client_scheme_types'),
        ('master', '0004_schemetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.vehicletype'),
        ),
    ]
