# Generated by Django 4.0 on 2026-05-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_schemetype'),
        ('client_management', '0016_customervehicle_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='next_renewal_date',
        ),
        migrations.AddField(
            model_name='client',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.district'),
        ),
    ]
