# Generated by Django 4.0 on 2026-05-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0017_remove_client_next_renewal_date_client_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='invoice_prefix',
            field=models.CharField(blank=True, help_text='Letter prefix for invoices (e.g. A → INV-A-1). Leave blank to auto-assign.', max_length=5, null=True),
        ),
    ]
