# Generated by Django 4.0 on 2026-05-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0019_subscriptionnotification_complainttype_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolve_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
