# Generated by Django 4.0 on 2026-06-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0023_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('Litre', 'Litre (Ltr)'), ('Millilitre', 'Millilitre (ml)'), ('Kilogram', 'Kilogram (Kg)'), ('Gram', 'Gram (g)'), ('Piece', 'Piece (Pcs)'), ('Box', 'Box'), ('Packet', 'Packet'), ('Bottle', 'Bottle'), ('Can', 'Can'), ('Roll', 'Roll')], max_length=50),
        ),
    ]
