# Generated by Django 4.0 on 2026-06-12 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_expense_expenseentry'),
        ('client_management', '0027_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='expense_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='master.expensehead'),
        ),
    ]
