# Generated by Django 4.0 on 2026-06-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0030_whatsappsetting_sender_id_whatsappsetting_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='whatsapp_attachments/'),
        ),
        migrations.AddField(
            model_name='whatsapptype',
            name='account',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='whatsapptype',
            name='message_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
