# Generated by Django 4.0 on 2026-07-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0032_renewaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
