# Generated by Django 4.0 on 2026-07-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0033_customervehicle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
