# Generated by Django 4.0 on 2026-07-02 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_vehiclecompany_vehiclecolor'),
        ('client_management', '0034_customervehicle_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervehicle',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.vehiclecolor'),
        ),
        migrations.AlterField(
            model_name='customervehicle',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.vehiclecompany'),
        ),
    ]
