# Generated by Django 4.0 on 2026-07-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0035_alter_customervehicle_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customervehicle',
            name='company',
        ),
    ]
