# Generated by Django 4.0 on 2026-07-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_vehiclebrandmodel_delete_vehiclecompany'),
        ('client_management', '0036_remove_customervehicle_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='brand_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.vehiclebrandmodel'),
        ),
    ]
