# Generated by Django 4.0 on 2026-07-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_seed_brand_models'),
        ('client_management', '0037_customervehicle_brand_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='enabled_vehicle_types',
            field=models.ManyToManyField(blank=True, related_name='enabled_branches', to='master.VehicleType'),
        ),
    ]
