# Generated by Django 4.0 on 2026-07-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_vehiclemake_alter_vehiclebrandmodel_unique_together_and_more'),
        ('client_management', '0038_branch_enabled_vehicle_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.vehiclemake'),
        ),
    ]
