# Generated by Django 4.0 on 2026-07-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0039_customervehicle_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsetting',
            name='is_official_api',
            field=models.BooleanField(default=False),
        ),
    ]
