# Generated by Django 4.0 on 2026-07-21 05:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('finance_management', '0007_invoice_invoice_type'),
        ('client_management', '0040_whatsappsetting_is_official_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='current_odometer_km',
            field=models.PositiveIntegerField(blank=True, help_text='Last recorded odometer reading (km)', null=True),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='last_oil_change_date',
            field=models.DateField(blank=True, help_text='Date of last oil change', null=True),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='last_tyre_change_date',
            field=models.DateField(blank=True, help_text='Date of last tyre change', null=True),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='next_oil_change_km',
            field=models.PositiveIntegerField(blank=True, help_text='Next recommended oil change at this km', null=True),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='next_tyre_change_km',
            field=models.PositiveIntegerField(blank=True, help_text='Next recommended tyre change at this km', null=True),
        ),
        migrations.CreateModel(
            name='VehicleOdometerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('odometer_km', models.PositiveIntegerField(help_text='Odometer reading in km')),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odometer_logs', to='finance_management.invoice')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_logs', to='client_management.customervehicle')),
            ],
            options={
                'ordering': ['-recorded_date'],
            },
        ),
    ]
