# Generated by Django 4.0 on 2026-07-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0041_add_slug_branch_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current stock quantity', max_digits=10),
        ),
    ]
