# Generated by Django 4.0 on 2026-08-11 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0014_seed_service_type_slugs'),
        ('client_management', '0044_quotation_quotationextra_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extras', to='service_management.servicetype'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_grand_total',
            field=models.BooleanField(default=True),
        ),
    ]
