# Generated by Django 4.0 on 2026-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0045_extra_service_type_quotation_is_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='last_smoke_test_date',
            field=models.DateField(blank=True, help_text='Date of last smoke test', null=True),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='next_smoke_test_date',
            field=models.DateField(blank=True, help_text='Recommended next smoke test renewal date', null=True),
        ),
    ]
