# Generated by Django 4.0 on 2026-08-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0046_customervehicle_last_smoke_test_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='base_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='cgst_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='conversion_count',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='critical_level',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Low stock alert level', max_digits=10),
        ),
    ]
