# Generated by Django 5.2.14 on 2026-08-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0048_stock_group_stock_hsn_code_stock_igst_percent_and_more'),
    ]

    operations = [
    ]
