# Generated by Django 4.0 on 2026-08-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0031_supplier_type_credit_limit_no_of_invoices'),
        ('client_management', '0050_stock_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='enabled_vehicle_segments',
            field=models.ManyToManyField(blank=True, related_name='enabled_branches', to='master.VehicleTypeModel'),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='last_alignment_date',
            field=models.DateField(blank=True, help_text='Date of last wheel alignment', null=True),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='next_alignment_km',
            field=models.PositiveIntegerField(blank=True, help_text='Next recommended wheel alignment at this km', null=True),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='wheel_type',
            field=models.CharField(choices=[('alloy_wheel', 'Alloy Wheel'), ('normal_wheel', 'Normal Wheel')], default='normal_wheel', max_length=20),
        ),
    ]
