# Generated by Django 4.0 on 2026-08-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0051_branch_enabled_vehicle_segments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='wawy_template_name',
            field=models.CharField(blank=True, default='', help_text='Wawy API template name (e.g. festivalgreeting). Leave blank for plain text sending.', max_length=100),
        ),
    ]
