# Generated by Django 4.0 on 2026-09-16 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0033_alter_vehicletypemodel_unique_together_and_more'),
        ('client_management', '0052_whatsapptemplate_wawy_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='emission_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_vehicles', to='master.emissionstandard'),
        ),
    ]
