# Generated by Django 4.0 on 2026-09-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0053_customervehicle_emission_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('LPG', 'LPG'), ('ELECTRIC', 'Electric')], max_length=20, null=True),
        ),
    ]
