# Generated by Django 4.0 on 2026-09-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0054_customervehicle_fuel_type_quotationextra_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationextra',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationextra',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
