# Generated by Django 4.0 on 2026-09-22 09:59

import client_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0055_quotationextra_quantity_quotationextra_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_seal',
            field=models.ImageField(blank=True, null=True, upload_to='client_seals/', validators=[client_management.models.validate_png, client_management.models.validate_image_dimensions]),
        ),
    ]
