# Generated by Django 4.0 on 2026-09-25 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0033_alter_vehicletypemodel_unique_together_and_more'),
        ('client_management', '0057_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='vehicle_details',
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_brand_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='master.vehiclebrandmodel'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='master.vehiclecolor'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='master.vehiclemake'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='master.vehicletype'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_type_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='master.vehicletypemodel'),
        ),
        migrations.AddField(
            model_name='lead',
            name='wheel_type',
            field=models.CharField(choices=[('alloy_wheel', 'Alloy Wheel'), ('normal_wheel', 'Normal Wheel')], default='normal_wheel', max_length=20),
        ),
    ]
