# Generated by Django 4.0 on 2026-10-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0059_add_corporate_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='Aadhaar number (required for Non-Motor customers)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_category',
            field=models.CharField(choices=[('motor', 'Motor'), ('non_motor', 'Non-Motor')], default='motor', help_text='Motor: has vehicle. Non-Motor: no vehicle (life/health insurance).', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth (required for Non-Motor customers)', null=True),
        ),
    ]
