# Generated by Django 4.2.30 on 2026-10-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0060_insurance_customer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, help_text='Tax / GST / TRN Number for Corporate customers', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tin_number',
            field=models.CharField(blank=True, help_text='TIN Number (optional)', max_length=100, null=True),
        ),
    ]
