# Generated by Django 4.2.30 on 2026-10-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0061_customer_tax_number_customer_tin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='client',
            name='tin_pan_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TIN No / PAN No'),
        ),
    ]
