# Generated by Django 6.0.4 on 2026-04-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='mode',
            field=models.CharField(choices=[('interstate', 'Interstate'), ('intrastate', 'Intrastate')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('tax_on_tax', 'Tax on Tax')], max_length=10),
        ),
    ]
