# Generated by Django 4.0 on 2026-06-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0002_bookingpause_bookingsettings_holidaycalendar_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyoffday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='whatsapp_welcome_message',
            field=models.TextField(blank=True, help_text='Custom welcome message. Use {customer_name}, {branch_name}, {company_name} as placeholders.', null=True),
        ),
    ]
