# Generated by Django 4.0 on 2026-06-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0004_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, help_text='Human-readable booking ID e.g. BK1, BK2', max_length=20, null=True, unique=True),
        ),
    ]
