# Generated by Django 4.0 on 2026-07-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0005_add_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='whatsapp_ready_message',
            field=models.TextField(blank=True, help_text='Ready alert message. Use {customer_name}, {vehicle_number}, {branch_name}, {company_name} as placeholders.', null=True),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='whatsapp_thanks_message',
            field=models.TextField(blank=True, help_text='Thank you message. Use {customer_name}, {vehicle_number}, {branch_name}, {company_name} as placeholders.', null=True),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='whatsapp_welcome_message',
            field=models.TextField(blank=True, help_text='Custom welcome message. Use {customer_name}, {vehicle_number}, {branch_name}, {company_name} as placeholders.', null=True),
        ),
    ]
