# Generated by Django 4.0 on 2026-07-09 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client_management', '0039_customervehicle_make'),
        ('service_management', '0012_change_service_fk_to_service'),
        ('finance_management', '0007_invoice_invoice_type'),
        ('booking_management', '0006_bookingsettings_whatsapp_ready_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reminder_message', models.TextField(help_text='Template for the reminder. Use placeholders: {customer_name}, {vehicle_number}, {service_name}')),
                ('days_after', models.PositiveIntegerField(help_text='Number of days after service to send this reminder')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reminders', to='client_management.branch')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='service_management.service')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentServiceReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reminders', to='finance_management.invoice')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_instances', to='booking_management.servicereminder')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
