# Generated by Django 4.0 on 2026-07-09 08:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client_management', '0039_customervehicle_make'),
        ('finance_management', '0007_invoice_invoice_type'),
        ('booking_management', '0007_servicereminder_sentservicereminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reminder_no', models.PositiveIntegerField(default=1)),
                ('scheduled_date', models.DateField()),
                ('is_sent', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_plans', to='client_management.branch')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to='auth.user')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_plans', to='finance_management.invoice')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_plans', to='booking_management.servicereminder')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
