# Generated by Django 4.2.27 on 2026-08-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0008_reminderplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereminder',
            name='template_name',
            field=models.CharField(blank=True, help_text='Official Wawy/WhatsApp template name (e.g. batteryservice, servicereminder)', max_length=100, null=True),
        ),
    ]
