# Generated by Django 4.0 on 2026-08-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0014_seed_service_type_slugs'),
        ('booking_management', '0010_servicereminder_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderplan',
            name='template_name',
            field=models.CharField(blank=True, help_text='Custom or rule template name (e.g. servicereminder, batteryservice)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reminderplan',
            name='reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_plans', to='booking_management.servicereminder'),
        ),
    ]
