# Generated by Django 4.0 on 2026-09-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0016_alter_smoketestprice_options_and_more'),
        ('booking_management', '0011_booking_service_booking_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='service_management.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
